version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: trends_birds_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: trends_user
      POSTGRES_PASSWORD: trends_pass
      POSTGRES_DB: trends_birds
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
